# Config file for automatic testing at travis-ci.org
dist: trusty
language: python
python:
  - 3.6
  - 3.5

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required

# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox

deploy:


  # Automatically build and deploy documentation to GitHub Pages after every
  # commit
  # Follow the instructions at https://docs.travis-ci.com/user/deployment/pages/
  # to setup a personal deployment token and then provide it as a secure
  # environment variable at https://travis-ci.org/DAI-Lab/CTGAN/settings
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
